name: gymklout
description: "Fitness, community, and motivation in one app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  intl: ^0.20.2
  fluentui_system_icons: ^1.1.273
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.4
  font_awesome_flutter: ^11.0.0
  shimmer: ^3.0.0
  local_auth: ^3.0.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  crypto: ^3.0.7
  flutter_dotenv: ^6.0.0
  lottie: ^3.3.2
  dio: ^5.9.2
  iconsax: ^0.0.8
  country_flags: ^4.1.2
  package_info_plus: ^9.0.1
  uuid: ^4.5.3
  app_links: ^7.1.1
  flutter_cache_manager: ^3.4.1
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.0.7
  image_cropper: ^12.2.1
  http_parser: ^4.1.2
  crop_your_image: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo/app_icon_foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/vectors/
    - assets/images/animations/
    - assets/images/logo/
    - .env

